"""empty message

Revision ID: 07e0c73a2f1b
Revises: a3b38527f923
Create Date: 2024-07-31 23:19:49.652744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e0c73a2f1b'
down_revision = 'a3b38527f923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_confirmed'), ['confirmed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_confirmed'))
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
