"""empty message

Revision ID: 0f77419633d8
Revises: a7219dce25c9
Create Date: 2024-08-05 21:28:26.208903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f77419633d8'
down_revision = 'a7219dce25c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
