"""empty message

Revision ID: 26daf3cc19d3
Revises: c804785d91e2
Create Date: 2024-08-02 10:35:45.993366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26daf3cc19d3'
down_revision = 'c804785d91e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
