"""empty message

Revision ID: c65d8561dc8e
Revises: 27fefa6eef0d
Create Date: 2024-08-01 17:45:08.781440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65d8561dc8e'
down_revision = '27fefa6eef0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('member_since',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('member_since',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
