"""empty message

Revision ID: db8d4748bc76
Revises: 15d62f205acd
Create Date: 2024-08-03 21:13:50.749845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8d4748bc76'
down_revision = '15d62f205acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['followed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###
