"""empty message

Revision ID: f257f02ece66
Revises: db8d4748bc76
Create Date: 2024-08-03 21:18:53.176721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f257f02ece66'
down_revision = 'db8d4748bc76'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('constraint'), 'users', ['followed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('constraint', type_='foreignkey')
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###
